### ISSUE TITLE
module db not found

### ISSUE THREAD

**Issue by jbescudie** [fnielsen/brede#13]
**Module db** (supposedly in db.py) is unknown and it causes an error when importing brede.

As a quick hack, I edited **brede/data/bredwiki.py** from : 

`class BredeWikiTemplates(db.DB):`

to

`class BredeWikiTemplates():`

**Comment by fnielsen** [comment]
Instead of erasing the db.DB I added db.py to the requirements.txt file

**Comment by fnielsen** [comment]
@jbescudie: Thanks for reporting it.
